FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRC_URI += " \
	file://0003-compositor-drm-Do-not-return-an-error-when-no-connec.patch \
	file://0004-compositor-drm-Do-not-exit-when-there-are-no-outputs.patch \
	file://0005-compositor-drm-Use-non-cast-functions-to-retrieve-ba.patch \
	file://0006-compositor-drm-support-RGB565-with-pixman-renderer.patch \
	file://0007-compositor-drm-Stop-sending-uninit-data-to-the-kerne.patch \
	file://0008-compositor-drm-Zero-drmModeAddFB2-data.patch \
	file://0009-compositor-drm-Comment-struct-members.patch \
	file://0010-compositor-drm-Simplify-drm_sprite_crtc_supported.patch \
	file://0011-compositor-drm-Extract-EGL-destroy-to-helper.patch \
	file://0012-compositor-drm-Use-fb-fd-consistently.patch \
	file://0013-compositor-drm-Use-signed-int-for-width-height.patch \
	file://0014-compositor-drm-Store-width-and-height-inside-drm_fb.patch \
	file://0015-compositor-drm-Delete-drm_backend_set_modes.patch \
	file://0016-compositor-drm-Remove-open-coded-weston_compositor_w.patch \
	file://0017-compositor-drm-Reshuffle-and-comment-plane-condition.patch \
	file://0018-compositor-drm-fix-a-couple-of-typos.patch \
	file://0019-compositor-drm-don-t-put-y-inverted-interlaced-botto.patch \
	file://0020-compositor-drm-Remove-crtc_allocator.patch \
	file://0021-compositor-drm-Avoid-connector_allocator-for-hotplug.patch \
	file://0022-compositor-drm-Remove-connector_allocator.patch \
	file://0023-timespec-Add-timespec_add_nsec-helper.patch \
	file://0024-timespec-Add-timespec_add_msec-helper.patch \
	file://0025-timespec-Add-timespec_to_msec-helper.patch \
	file://0026-timespec-Add-timespec-subtraction-helpers.patch \
	file://0027-Calculate-next-frame-target-time-in-absolute-space.patch \
	file://0028-Don-t-delay-initial-output-paint.patch \
	file://0029-Change-repaint_needed-to-bool.patch \
	file://0030-Add-comments-and-whitespace-to-repaint-machinery.patch \
	file://0031-libweston-grammar-fix-to-recent-comment.patch \
	file://0032-Change-boolean-repaint_scheduled-to-quad-state-enum.patch \
	file://0033-Switch-to-global-output-repaint-timer.patch \
	file://0034-Allow-backends-to-group-repaint-flushes.patch \
	file://0035-libweston-Add-pixel-format-helpers.patch \
	file://0036-compositor-drm-Calculate-more-cursor-state-up-front.patch \
	file://0037-compositor-drm-Add-explicit-type-member-to-drm_fb.patch \
	file://0038-compositor-drm-Store-format-in-drm_fb.patch \
	file://0039-compositor-drm-Refactor-destroy-drm_fb-function.patch \
	file://0040-compositor-drm-Drop-output-from-release_fb.patch \
	file://0041-compositor-drm-Refcount-drm_fb.patch \
	file://0042-compositor-drm-Use-refcounted-FBs-for-Pixman.patch \
	file://0043-compositor-drm-Use-drm_fb-for-cursor-buffers.patch \
	file://0044-compositor-drm-Rename-current-next-FB-members.patch \
	file://0045-compositor-drm-Reshuffle-drm_output_render.patch \
	file://0046-compositor-drm-Return-FB-directly-from-render.patch \
	file://0047-compositor-drm-Introduce-fb_last-member.patch \
	file://0048-compositor-drm-Turn-vblank_pending-from-bool-to-refc.patch \
	file://0049-compositor-drm-Clean-up-page_flip_pending-path.patch \
	file://0050-compositor-drm-Rename-drm_sprite-to-drm_plane.patch \
	file://0051-compositor-drm-Refactor-sprite-create-destroy-into-h.patch \
	file://0052-compositor-drm-Rename-fb_plane-to-scanout_plane.patch \
	file://0053-compositor-drm-Add-DRM-property-cache.patch \
	file://0054-compositor-drm-Add-universal-plane-awareness.patch \
	file://0055-compositor-drm-Track-all-plane-types.patch \
	file://0056-compositor-drm-Make-scanout-view-preparation-more-st.patch \
	file://0057-compositor-drm-Introduce-drm_pending_state-structure.patch \
	file://0058-compositor-drm-Introduce-drm_output_state-structure.patch \
	file://0059-compositor-drm-Introduce-drm_plane_state-structure.patch \
	file://0060-compositor-drm-Track-cursor_plane-with-a-drm_plane.patch \
	file://0061-compositor-drm-Use-drm_plane-for-scanout-plane.patch \
	file://0062-compositor-drm-Don-t-repaint-if-no-damage.patch \
	file://0063-compositor-drm-Track-unused-connectors-and-CRTCs.patch \
	file://0064-compositor-drm-Disable-unused-CRTCs-connectors.patch \
	file://0065-compositor-drm-Move-repaint-state-application-to-flu.patch \
	file://0066-compositor-drm-Use-apply_state-for-starting-repaint.patch \
	file://0067-compositor-drm-Don-t-restore-original-CRTC-mode.patch \
	file://0068-compositor-drm-Discover-atomic-properties.patch \
	file://0069-compositor-drm-Add-blob_id-member-to-drm_mode.patch \
	file://0070-compositor-drm-Add-to_drm_mode-helper.patch \
	file://0071-compositor-drm-Atomic-modesetting-support.patch \
	file://0072-compositor-drm-Make-alpha-to-opaque-handling-common.patch \
	file://0073-compositor-drm-Extract-buffer-plane-co-ord-translati.patch \
	file://0074-compositor-drm-Fully-account-for-buffer-transformati.patch \
	file://0075-compositor-drm-Only-disallow-scaling-for-overlay-pla.patch \
	file://0076-compositor-drm-Use-plane_state_coords_for_view-for-s.patch \
	file://0077-compositor-drm-Use-plane_coords_for_view-for-cursor.patch \
	file://0078-compositor-drm-Extract-overlay-FB-import-to-helper.patch \
	file://0079-compositor-drm-Use-plane-FB-import-helper-for-scanou.patch \
	file://0080-compositor-drm-Remove-no_addfb2-handling.patch \
	file://0081-compositor-drm-Extract-drm_fb_addfb-into-a-helper.patch \
	file://0082-compositor-drm-Support-multi-planar-drm_fb.patch \
	file://0083-compositor-drm-Avoid-GBM-for-dmabuf-import.patch \
	file://0084-compositor-drm-Support-modifiers-for-drm_fb.patch \
	file://0085-compositor-drm-Don-t-need-safe-view-list-traversal.patch \
	file://0086-compositor-drm-Rename-region-variable.patch \
	file://0087-compositor-drm-Split-drm_assign_planes-in-two.patch \
	file://0088-compositor-drm-Ignore-views-on-other-outputs.patch \
	file://0089-compositor-drm-Ignore-occluded-views.patch \
	file://0090-compositor-drm-Add-modes-to-drm_output_propose_state.patch \
	file://0091-compositor-drm-Return-plane-state-from-plane-prepara.patch \
	file://0092-compositor-drm-Add-test-only-mode-to-state-applicati.patch \
	file://0093-compositor-drm-Relax-plane-restrictions-for-atomic.patch \
	file://0094-compositor-drm-Enable-planes-for-atomic.patch \
"

SRC_URI += " \
	file://1001-gl-renderer-add-WL_SHM_FORMAT_YUV420-WL_SHM_FORMAT_N.patch \
	file://1002-compositor-set-DEFAULT_REPAINT_WINDOW-15.patch \
	file://1003-weston-support-drm-nv12_10-video-overlay.patch \
"